name: 'AWS Instance Ripper Reporter'
description: 'GitHub Actions to display the report from the aws-instance-ripper action as an issue comment'
inputs:
  data:  
    description: 'The data to print'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'cloud-lightning'  
  color: 'red'