name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: AWS Ripper
      uses: helaili/aws-instance-ripper@c718a4d
      id: ripper
      with:
        AWSAccessKeyID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWSSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        defaultStopDelay: 21
        defaultTerminateDelay: 28
        dryRun: true
    - name: AWS Ripper Reporting
      uses: ./
      with:
        data: ${{ steps.ripper.outputs.report }}
    